import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const Cormorant = Cormorant_Garamond({
    variable: "--font-cormorant-sans",
    subsets: ["latin"],
    weight: "300",
});

export const metadata: Metadata = {
    title: "Secret App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${Cormorant.variable} antialiased bg-color-md text-white`}
            >
                <div className="p-4">{children}</div>
            </body>
        </html>
    );
}
